### PR TITLE
Add `pddp` ELISA deployments

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Comment by jcpunk** [comment]
Once merged, does this need to be deployed at NP04?

**Review by jcpunk — APPROVED** [review]

**Comment by plasorak** [comment]
Yes

**Comment by plasorak** [comment]
But I believe we need: https://github.com/DUNE-DAQ/microservices/pull/119 before (and therefore a new image)

**Review by jcpunk — APPROVED** [review]
No objection from me, when do you want this stood up at NP04?

**Comment by plasorak** [comment]
I'd say we should do that when its the least disruptive for operations. Let me check with Wes.

**Pull request merged**
